<a href="https://colab.research.google.com/github/Sezikeye/Assignment-AI/blob/main/AI_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
stocks = pd.read_csv('historical_stocks.csv')
prices = pd.read_csv('historical_stock_prices.csv')

In [3]:
# Preview data
print(stocks.head())
print(prices.head())

  ticker exchange                                    name             sector  \
0    PIH   NASDAQ  1347 PROPERTY INSURANCE HOLDINGS, INC.            FINANCE
1  PIHPP   NASDAQ  1347 PROPERTY INSURANCE HOLDINGS, INC.            FINANCE
2   TURN   NASDAQ                180 DEGREE CAPITAL CORP.            FINANCE
3   FLWS   NASDAQ                 1-800 FLOWERS.COM, INC.  CONSUMER SERVICES
4   FCCY   NASDAQ           1ST CONSTITUTION BANCORP (NJ)            FINANCE

                     industry
0  PROPERTY-CASUALTY INSURERS
1  PROPERTY-CASUALTY INSURERS
2  FINANCE/INVESTORS SERVICES
3      OTHER SPECIALTY STORES
4        SAVINGS INSTITUTIONS
  ticker   open  close  adj_close    low   high   volume        date
0    AHH  11.50  11.58   8.493155  11.25  11.68  4633900  2013-05-08
1    AHH  11.66  11.55   8.471151  11.50  11.66   275800  2013-05-09
2    AHH  11.55  11.60   8.507822  11.50  11.60   277100  2013-05-10
3    AHH  11.63  11.65   8.544494  11.55  11.65   147400  2013-05-13
4    AHH  11.60  11.53   8.456484  11.50  11.60   184100  2013-05-14

In [4]:
# Check structure
print(stocks.info())
print(prices.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6460 entries, 0 to 6459
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ticker    6460 non-null   object
 1   exchange  6460 non-null   object
 2   name      6460 non-null   object
 3   sector    5020 non-null   object
 4   industry  5020 non-null   object
dtypes: object(5)
memory usage: 252.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20973889 entries, 0 to 20973888
Data columns (total 8 columns):
 #   Column     Dtype
---  ------     -----
 0   ticker     object
 1   open       float64
 2   close      float64
 3   adj_close  float64
 4   low        float64
 5   high       float64
 6   volume     int64
 7   date       object
dtypes: float64(5), int64(1), object(2)
memory usage: 1.3+ GB
None

In [5]:

# Check missing values
print(prices.isnull().sum())
print(stocks.isnull().sum())

ticker       0
open         0
close        0
adj_close    0
low          0
high         0
volume       0
date         0
dtype: int64
ticker         0
exchange       0
name           0
sector      1440
industry    1440
dtype: int64

In [6]:
stocks["sector"].fillna("Unknown", inplace=True)
stocks["industry"].fillna("Unknown", inplace=True)

/tmp/ipykernel_86281/3343637660.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  stocks["sector"].fillna("Unknown", inplace=True)
/tmp/ipykernel_86281/3343637660.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  stocks["industry"].fillna("Unknown", inplace=True)

In [7]:
print(prices.isnull().sum())
print(stocks.isnull().sum())

ticker       0
open         0
close        0
adj_close    0
low          0
high         0
volume       0
date         0
dtype: int64
ticker      0
exchange    0
name        0
sector      0
industry    0
dtype: int64

In [8]:
# checking for duplicates
stocks.duplicated().sum()
prices.duplicated().sum()

np.int64(0)

In [9]:
import pandas as pd
prices = pd.read_csv('historical_stock_prices.csv')
stocks = pd.read_csv('historical_stocks.csv')

# We merge the 2 dataset
merged= pd.merge(prices, stocks, on='ticker', how='left')
print(merged.head())

  ticker   open  close  adj_close    low   high   volume        date exchange  \
0    AHH  11.50  11.58   8.493155  11.25  11.68  4633900  2013-05-08     NYSE
1    AHH  11.66  11.55   8.471151  11.50  11.66   275800  2013-05-09     NYSE
2    AHH  11.55  11.60   8.507822  11.50  11.60   277100  2013-05-10     NYSE
3    AHH  11.63  11.65   8.544494  11.55  11.65   147400  2013-05-13     NYSE
4    AHH  11.60  11.53   8.456484  11.50  11.60   184100  2013-05-14     NYSE

                              name   sector     industry
0  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE
1  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE
2  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE
3  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE
4  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE

In [10]:
# we add decade column
merged["date"] = pd.to_datetime(merged["date"], errors='coerce')
merged["decade"] = (merged["date"].dt.year // 10) * 10
print(merged.head())

  ticker   open  close  adj_close    low   high   volume       date exchange  \
0    AHH  11.50  11.58   8.493155  11.25  11.68  4633900 2013-05-08     NYSE
1    AHH  11.66  11.55   8.471151  11.50  11.66   275800 2013-05-09     NYSE
2    AHH  11.55  11.60   8.507822  11.50  11.60   277100 2013-05-10     NYSE
3    AHH  11.63  11.65   8.544494  11.55  11.65   147400 2013-05-13     NYSE
4    AHH  11.60  11.53   8.456484  11.50  11.60   184100 2013-05-14     NYSE

                              name   sector     industry  decade
0  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
1  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
2  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
3  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
4  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010

In [11]:
# we create statiscal values for merged data
merged.describe()

,open,close,adj_close,low,high,volume,date,decade
count,2.097389e+07,2.097389e+07,2.097389e+07,2.097389e+07,2.097389e+07,2.097389e+07,20973889,2.097389e+07
mean,7.605823e+01,7.611403e+01,1.481184e+14,7.422064e+01,7.803857e+01,1.227043e+06,2006-05-19 00:44:53.227565184,2.001181e+03
min,4.000000e-04,2.000000e-04,2.282650e-09,1.000000e-04,4.000000e-04,1.000000e+00,1970-01-02 00:00:00,1.970000e+03
25%,7.500000e+00,7.500000e+00,4.620000e+00,7.360000e+00,7.630000e+00,2.210000e+04,2000-05-09 00:00:00,2.000000e+03
50%,1.545000e+01,1.545000e+01,1.138199e+01,1.524000e+01,1.566000e+01,1.260000e+05,2008-07-29 00:00:00,2.000000e+03
75%,2.972000e+01,2.972000e+01,2.472046e+01,2.928000e+01,3.010000e+01,6.074000e+05,2014-05-30 00:00:00,2.010000e+03
max,2.034000e+06,1.779750e+06,1.894962e+19,1.440000e+06,2.070000e+06,4.483504e+09,2018-08-24 00:00:00,2.010000e+03
std,2.849639e+03,2.870159e+03,4.574674e+16,2.746059e+03,2.997937e+03,1.316686e+07,NaN,9.725233e+00

In [12]:
# checking  missing value formerged
merged.isnull().sum()

ticker             0
open               0
close              0
adj_close          0
low                0
high               0
volume             0
date               0
exchange           0
name               0
sector       2549449
industry     2549449
decade             0
dtype: int64

In [13]:
# Handling  missing values
merged= merged.fillna(method="ffill")

/tmp/ipykernel_86281/922380540.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  merged= merged.fillna(method="ffill")

In [14]:
merged.isna().sum()

ticker       0
open         0
close        0
adj_close    0
low          0
high         0
volume       0
date         0
exchange     0
name         0
sector       0
industry     0
decade       0
dtype: int64

In [15]:
print(merged.head())

  ticker   open  close  adj_close    low   high   volume       date exchange  \
0    AHH  11.50  11.58   8.493155  11.25  11.68  4633900 2013-05-08     NYSE
1    AHH  11.66  11.55   8.471151  11.50  11.66   275800 2013-05-09     NYSE
2    AHH  11.55  11.60   8.507822  11.50  11.60   277100 2013-05-10     NYSE
3    AHH  11.63  11.65   8.544494  11.55  11.65   147400 2013-05-13     NYSE
4    AHH  11.60  11.53   8.456484  11.50  11.60   184100 2013-05-14     NYSE

                              name   sector     industry  decade
0  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
1  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
2  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
3  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
4  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010

In [16]:
# Visualization

In [17]:
print (merged.head())

  ticker   open  close  adj_close    low   high   volume       date exchange  \
0    AHH  11.50  11.58   8.493155  11.25  11.68  4633900 2013-05-08     NYSE
1    AHH  11.66  11.55   8.471151  11.50  11.66   275800 2013-05-09     NYSE
2    AHH  11.55  11.60   8.507822  11.50  11.60   277100 2013-05-10     NYSE
3    AHH  11.63  11.65   8.544494  11.55  11.65   147400 2013-05-13     NYSE
4    AHH  11.60  11.53   8.456484  11.50  11.60   184100 2013-05-14     NYSE

                              name   sector     industry  decade
0  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
1  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
2  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
3  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010
4  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE    2010

In [18]:
# rolling average
merged['sma_5'] = merged['close'].rolling(5).mean()
merged['sma_10'] = merged['close'].rolling(10).mean()
merged['sma_20'] = merged['close'].rolling(20).mean()

merged['price_vs_sma20'] = merged['close'] - merged['sma_20']

In [19]:
processed = []

for decade, df in merged.items():
    df = df.copy()

    # ensure DataFrame
    if isinstance(df, pd.Series):
        df = df.to_frame()

    df.columns = df.columns.str.lower()

    processed.append(df)